# Milestone 2: Skill Extraction, Similarity and Evaluation

Run Notebook 01 first to regenerate the processed CSVs from the full raw datasets. Run these cells in order from the project root or `notebooks/`. The skill dictionary and aggregate evaluations use all processed records; individual resume/job examples are retained. `partial` supplies shared inputs to imported functions so later calls keep their original shape.

## 1. Setup and Data Loading

### Import libraries and project functions

In [1]:
# Import libraries and reusable project functions.
import ast
import sys
from functools import partial
from pathlib import Path

import pandas as pd

# Support execution from the project root or notebooks/.
PROJECT_ROOT = Path.cwd() if (Path.cwd() / "src").is_dir() else Path.cwd().parent
DATA_DIR = PROJECT_ROOT / "data"
sys.path.insert(0, str(PROJECT_ROOT))
from src.skill_extraction import (
    build_skill_dictionary,
    create_skill_extractor,
    extract_skills,
    prepare_optimized_extractor,
    optimize_skill_dictionary,
    create_optimized_extractor,
    extract_skills_optimized,
)
from src.similarity import compare_skills, filter_generic_skills, calculate_skill_match
from src.pipeline import analyze_match
from src.evaluation import (
    evaluate_single_resume,
    evaluate_resumes,
    evaluate_optimized_resumes,
    compare_evaluation_results,
)

### Load the processed resumes and jobs

In [2]:
cv = pd.read_csv(DATA_DIR / "processed" / "final_cleaned_cv.csv")
jobs = pd.read_csv(DATA_DIR / "processed" / "final_cleaned_jobs.csv")

# Reject old sample-derived exports before running the analysis.
raw_candidate_ids = pd.read_csv(DATA_DIR / "raw" / "cv.csv", usecols=["candidate_id"])
raw_job_ids = pd.read_csv(DATA_DIR / "raw" / "job.csv", usecols=["job_id"])
if (set(cv["candidate_id"]) != set(raw_candidate_ids["candidate_id"])
        or set(jobs["job_id"]) != set(raw_job_ids["job_id"])):
    raise ValueError("Processed data does not cover the raw datasets. Run Notebook 01 first.")

print("CV shape:", cv.shape)
print("Jobs shape:", jobs.shape)

CV shape: (9544, 15)
Jobs shape: (1167, 13)

### Convert resume skill labels into lists

In [3]:
# Convert resume skills from text into Python lists
cv["skills_list"] = cv["clean_skills"].apply(ast.literal_eval)

cv[["target_position", "skills_list"]].head()

,target_position,skills_list
0,Senior Software Engineer,"[big data, hadoop, hive, python, mapreduce, sp..."
1,Machine Learning (ML) Engineer,"[data analysis, data analytics, business analy..."
2,"Executive/ Senior Executive- Trade Marketing, ...","[software development, machine learning, deep ..."
3,Business Development Executive,"[accounts payables, accounts receivables, acco..."
4,Senior iOS Engineer,"[analytical reasoning, compliance testing know..."

### Convert job skill labels into lists

In [4]:
# Convert job skills from text into Python lists

jobs["skills_list"] = jobs["clean_skills"].apply(ast.literal_eval)

jobs[["job_title", "skills_list"]].head()

,job_title,skills_list
0,Director of Finance,"[financial management, accounting, gaap princi..."
1,Human Resources Manager,"[recruiting, talent management, compliance, em..."
2,Salesperson,"[sales, customer relationship management, tech..."
3,Business Development Manager,"[account management, client relationship manag..."
4,AOC Human Resources Project Manager,"[project management, human resources administr..."

## 2. AI/NLP Model: Skill Extraction

### Build the skill dictionary

In [5]:
skill_dictionary = build_skill_dictionary(cv, jobs)

Number of unique skills: 8078

Sample skills:
['.net', '.net programming', '.ney vb asp', '10key by touch', '15+ years of experience in accounting bookkeeping services', '2-tier', '2000', '2k', '3-d noise mapping', '3cx', '3d', '3d modeling', '3d printing', '3ds max', '3dsmax', '3pl services', '401 k administration', '401 k management', '401k administration', '401k knowledge', '401k rollovers', '5 why', '5s', '5s expert', '5s methodologies', '5s technique', '6sense', '8d', 'a highly motivated and energetic personality.', 'a+']

### Create the EntityRuler and prepare skill extraction

In [6]:
nlp = create_skill_extractor(skill_dictionary)
extract_skills = partial(extract_skills, nlp=nlp)

Number of skill patterns: 8078

### Extract skills from one resume

In [7]:
# Test skill extraction on one resume

extracted_resume_skills = extract_skills(
    cv.loc[0, "processed_resume"]
)

print("Extracted Resume Skills:")
print(extracted_resume_skills)

Extracted Resume Skills:
['rdbms', 'cloud infrastructure', 'development', 'amazon redshift', 'troubleshooting', 'machine learning', 'electronics', 'yarn', 'big data', 'hdfs', 'skills', 'technical support', 'spark', 'analyst', 'core java', 'data structures', 'mentorship', 'java', 'engineering', 'c++', 'software', 'big data analytics', 'software engineer', 'data science', 'computer science', 'deployment', 'hadoop', 'database', 'technology', 'talend', 'dbms', 'microsoft azure', 'python', 'mapreduce', 'hive', 'informatica', 'cloud', 'services']

### Extract skills from one job description

In [8]:
# Extract skills from one job description

extracted_job_skills = extract_skills(
    jobs.loc[0, "processed_job"]
)

print("Extracted Job Skills:")
print(extracted_job_skills)

Extracted Job Skills:
['delivery', 'microsoft office suite', 'operations', 'risk management', 'sustainability', 'financial', 'plan', 'account reconciliations', 'contracts', 'responsibility', 'strategic plan', 'insight', 'purchasing', 'information technology', 'insurance', 'investment oversight', 'financial management', 'written', 'employee benefits', 'driving', 'cash flow', 'coordination', 'financial statement preparation', 'processes', 'services', 'compliance', 'controller', 'meetings', 'interpersonal', 'budget processes', 'quality', 'administrative', 'internal controls', 'benefits', 'results oriented', 'its', 'accounts receivable accounts payable', 'policies', 'audit', 'staff', 'cash flow analysis', 'tax', 'next', 'gaap principles', 'self motivated', 'cash flow management', 'confidentiality', 'safety', 'direction', 'cost analysis', 'retail', 'banking', 'raiser s edge software', 'budgets', 'hardware', 'financial audit', 'financial analysis', 'pos systems', 'business', 'assist', 'integration', 'consistency', 'developing', 'it support services', 'legal', 'accounts payable', 'revenues', 'passionate', 'mba', 'finance', 'mentorship', 'payroll', 'software', 'forecasts', 'budgeting and forecasting', 'support', 'investment management', 'business administration', 'facilities management', 'accounting', 'drafting', 'development', 'analytical', 'type', 'budget', 'human resources', 'capital projects', 'bi', 'organizational', 'degree in accounting', 'director', 'microsoft', 'treasury', 'senior management', 'contract management', 'network', 'government', 'cpa', 'act', 'negotiating', 'trust', 'financing strategies', 'asset allocation']

## 3. Matched Skills, Missing Skills and Skill Percentage

### Compare the extracted resume and job skills

In [9]:
matched_skills, missing_skills = compare_skills(
    extracted_resume_skills, extracted_job_skills
)

Matched Skills:
['development', 'software', 'mentorship', 'services']

Missing Skills:
['delivery', 'microsoft office suite', 'operations', 'risk management', 'sustainability', 'financial', 'plan', 'account reconciliations', 'contracts', 'responsibility', 'strategic plan', 'insight', 'purchasing', 'information technology', 'insurance', 'investment oversight', 'financial management', 'written', 'employee benefits', 'driving', 'cash flow', 'coordination', 'financial statement preparation', 'processes', 'compliance', 'controller', 'meetings', 'interpersonal', 'budget processes', 'quality', 'administrative', 'internal controls', 'benefits', 'results oriented', 'its', 'accounts receivable accounts payable', 'policies', 'audit', 'staff', 'cash flow analysis', 'tax', 'next', 'gaap principles', 'self motivated', 'cash flow management', 'confidentiality', 'safety', 'direction', 'cost analysis', 'retail', 'banking', 'raiser s edge software', 'budgets', 'hardware', 'financial audit', 'financial analysis', 'pos systems', 'business', 'assist', 'integration', 'consistency', 'developing', 'it support services', 'legal', 'accounts payable', 'revenues', 'passionate', 'mba', 'finance', 'payroll', 'forecasts', 'budgeting and forecasting', 'support', 'investment management', 'business administration', 'facilities management', 'accounting', 'drafting', 'analytical', 'type', 'budget', 'human resources', 'capital projects', 'bi', 'organizational', 'degree in accounting', 'director', 'microsoft', 'treasury', 'senior management', 'contract management', 'network', 'government', 'cpa', 'act', 'negotiating', 'trust', 'financing strategies', 'asset allocation']

### Remove generic terms from the extracted skills

In [10]:
extracted_resume_skills, extracted_job_skills = filter_generic_skills(
    extracted_resume_skills, extracted_job_skills
)

Cleaned Resume Skills:
['rdbms', 'cloud infrastructure', 'amazon redshift', 'troubleshooting', 'machine learning', 'electronics', 'yarn', 'big data', 'hdfs', 'skills', 'technical support', 'spark', 'analyst', 'core java', 'data structures', 'mentorship', 'java', 'engineering', 'c++', 'software', 'big data analytics', 'software engineer', 'data science', 'computer science', 'deployment', 'hadoop', 'technology', 'talend', 'dbms', 'microsoft azure', 'python', 'mapreduce', 'hive', 'informatica', 'cloud']

Cleaned Job Skills:
['delivery', 'microsoft office suite', 'operations', 'risk management', 'sustainability', 'plan', 'account reconciliations', 'contracts', 'responsibility', 'strategic plan', 'insight', 'purchasing', 'information technology', 'insurance', 'investment oversight', 'financial management', 'employee benefits', 'driving', 'cash flow', 'coordination', 'financial statement preparation', 'processes', 'compliance', 'controller', 'meetings', 'interpersonal', 'budget processes', 'quality', 'administrative', 'internal controls', 'benefits', 'results oriented', 'its', 'accounts receivable accounts payable', 'policies', 'audit', 'staff', 'cash flow analysis', 'tax', 'next', 'gaap principles', 'self motivated', 'cash flow management', 'confidentiality', 'safety', 'cost analysis', 'retail', 'banking', 'raiser s edge software', 'budgets', 'hardware', 'financial audit', 'financial analysis', 'pos systems', 'business', 'assist', 'integration', 'consistency', 'developing', 'it support services', 'legal', 'accounts payable', 'revenues', 'passionate', 'mba', 'finance', 'mentorship', 'payroll', 'software', 'forecasts', 'budgeting and forecasting', 'support', 'investment management', 'business administration', 'facilities management', 'accounting', 'drafting', 'analytical', 'type', 'budget', 'human resources', 'capital projects', 'bi', 'organizational', 'degree in accounting', 'director', 'microsoft', 'treasury', 'senior management', 'contract management', 'network', 'government', 'cpa', 'act', 'negotiating', 'trust', 'financing strategies', 'asset allocation']

### Compare the filtered skills

In [11]:
matched_skills, missing_skills = compare_skills(
    extracted_resume_skills, extracted_job_skills
)

Matched Skills:
['software', 'mentorship']

Missing Skills:
['delivery', 'microsoft office suite', 'operations', 'risk management', 'sustainability', 'plan', 'account reconciliations', 'contracts', 'responsibility', 'strategic plan', 'insight', 'purchasing', 'information technology', 'insurance', 'investment oversight', 'financial management', 'employee benefits', 'driving', 'cash flow', 'coordination', 'financial statement preparation', 'processes', 'compliance', 'controller', 'meetings', 'interpersonal', 'budget processes', 'quality', 'administrative', 'internal controls', 'benefits', 'results oriented', 'its', 'accounts receivable accounts payable', 'policies', 'audit', 'staff', 'cash flow analysis', 'tax', 'next', 'gaap principles', 'self motivated', 'cash flow management', 'confidentiality', 'safety', 'cost analysis', 'retail', 'banking', 'raiser s edge software', 'budgets', 'hardware', 'financial audit', 'financial analysis', 'pos systems', 'business', 'assist', 'integration', 'consistency', 'developing', 'it support services', 'legal', 'accounts payable', 'revenues', 'passionate', 'mba', 'finance', 'payroll', 'forecasts', 'budgeting and forecasting', 'support', 'investment management', 'business administration', 'facilities management', 'accounting', 'drafting', 'analytical', 'type', 'budget', 'human resources', 'capital projects', 'bi', 'organizational', 'degree in accounting', 'director', 'microsoft', 'treasury', 'senior management', 'contract management', 'network', 'government', 'cpa', 'act', 'negotiating', 'trust', 'financing strategies', 'asset allocation']

### Calculate the skill-match percentage

In [12]:
skill_match_percentage = calculate_skill_match(matched_skills, extracted_job_skills)

Skill Match Percentage: 2.04 %

## 4. TF-IDF + Cosine Similarity

### Prepare the optimized extractor for the example analysis

In [13]:
optimized_nlp = prepare_optimized_extractor(cv, jobs)
extract_skills_optimized = partial(extract_skills_optimized, optimized_nlp=optimized_nlp)
analyze_match = partial(
    analyze_match,
    cv=cv,
    jobs=jobs,
    extract_skills_optimized=extract_skills_optimized,
)

### Analyze one resume against one job

In [14]:
# Test the analyzer

analyze_match(3, 3)

Resume: Business Development Executive
Job: Business Development Manager

Matched Skills:
['business development', 'business', 'sourcing', 'clients', 'skills']

Missing Skills:
['staffing', 'contractor staffing', 'requirement', 'type', 'it staffing', 'recruitment', 'market', 'revenue targets', 'software solutions', 'aggressive', 'it services', 'talent acquisition', 'account management', 'energetic', 'placing', 'basis', 'project', 'technical recruitment', 'client', 'client relationship management', 'accountable for', 'target oriented', 'support', 'self motivated', 'articulate', 'employment']

Skill Match Percentage: 16.13 %
Text Similarity Percentage: 11.68 %

{'resume_position': 'Business Development Executive',
 'job_title': 'Business Development Manager',
 'matched_skills': ['business development',
  'business',
  'sourcing',
  'clients',
  'skills'],
 'missing_skills': ['staffing',
  'contractor staffing',
  'requirement',
  'type',
  'it staffing',
  'recruitment',
  'market',
  'revenue targets',
  'software solutions',
  'aggressive',
  'it services',
  'talent acquisition',
  'account management',
  'energetic',
  'placing',
  'basis',
  'project',
  'technical recruitment',
  'client',
  'client relationship management',
  'accountable for',
  'target oriented',
  'support',
  'self motivated',
  'articulate',
  'employment'],
 'skill_match_percentage': 16.13,
 'text_similarity_percentage': np.float64(11.68)}

## 5. Baseline Evaluation

### Measure precision, recall and F1 for one resume

In [15]:
precision, recall, f1 = evaluate_single_resume(cv, extract_skills)

Precision: 0.55
Recall: 1.0
F1-score: 0.71

### Evaluate the baseline extractor across all resumes

In [16]:
precision_scores, recall_scores, f1_scores = evaluate_resumes(cv, extract_skills)

Average Precision: 0.56
Average Recall: 0.97
Average F1-score: 0.7

## 6. Dictionary Optimization and Final Evaluation

### Filter the complete skill dictionary

In [17]:
optimized_skill_dictionary = optimize_skill_dictionary(skill_dictionary)

Original skills: 8078
Optimized skills: 8065

### Rebuild the optimized EntityRuler

In [18]:
optimized_nlp = create_optimized_extractor(optimized_skill_dictionary)
extract_skills_optimized = partial(extract_skills_optimized, optimized_nlp=optimized_nlp)
analyze_match = partial(analyze_match, extract_skills_optimized=extract_skills_optimized)

Optimized skill patterns: 8065

### Evaluate the optimized extractor across all resumes

In [19]:
optimized_precision, optimized_recall, optimized_f1 = evaluate_optimized_resumes(
    cv, extract_skills_optimized
)

Optimized Average Precision: 0.57
Optimized Average Recall: 0.96
Optimized Average F1-score: 0.7

### Compare baseline and optimized metrics on the full resume dataset

In [20]:
compare_evaluation_results(
    optimized_precision, optimized_recall, optimized_f1,
    baseline_precision=sum(precision_scores) / len(precision_scores),
    baseline_recall=sum(recall_scores) / len(recall_scores),
    baseline_f1=sum(f1_scores) / len(f1_scores),
)

Before Optimization
Precision: 0.56
Recall: 0.97
F1-score: 0.7

After Optimization
Precision: 0.57
Recall: 0.96
F1-score: 0.7